services:
  web:
    build: .
    container_name: msx-flask-web
    ports:
      - "${HOST_PORT:-80}:5001"
    volumes:
      - ./files:/app/files
      - ./app.py:/app/app.py:ro
      - ./utils.py:/app/utils.py:ro
      - ./translations.py:/app/translations.py:ro
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro
      - ./requirements.txt:/app/requirements.txt:ro
    env_file:
      - .env
    restart: unless-stopped
